### ISSUE TITLE
facing issues while running tfrecord code:

### ISSUE THREAD

**Issue by Balamurugan-R** [RomRoc/objdet_train_tensorflow_colab#4]
facing issues while running tfrecord code:

!python ~/models/research/object_detection/dataset_tools/create_pet_tf_record.py --label_map_path=label_map.pbtxt --data_dir=. --output_dir=. --num_shards=1

ERROR

/root/datalab
Traceback (most recent call last):
  File "/root/models/research/object_detection/dataset_tools/create_pet_tf_record.py", line 318, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/models/research/object_detection/dataset_tools/create_pet_tf_record.py", line 271, in main
    label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/utils/label_map_util.py", line 164, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/utils/label_map_util.py", line 138, in load_labelmap
    label_map.ParseFromString(label_map_string)
google.protobuf.message.DecodeError: Error parsing message

@RomRoc any help will be great .

_Originally posted by @sam-ai in https://github.com/RomRoc/objdet_train_tensorflow_colab/issues/3#issuecomment-449877789_

**Comment by sam-ai** [comment]
Check this it's working but Done all in a hurry 💯 : https://colab.research.google.com/drive/1U6naXzr5F9HyNkFZBZlUHOsqk4uYxzJP

**Comment by sam-ai** [comment]
Change this -> !echo "item {\n id: 1\n name: 'dog'\n}" -> label_map.pbtxt to !echo "item { id: 1 name: 'dog'}" > label_map.pbtxt, tfrecord will work

**Comment by divyanshgaur** [comment]
![capture](https://user-images.githubusercontent.com/42156673/50753100-b09c8780-1276-11e9-9b3b-5ca66d36ea0b.JPG)
